### ISSUE TITLE
navbar

### ISSUE THREAD

**Issue by Qurbonov** [safak/react-estate-ui#8]
responsive  navbar is visibile when normal size ? 

![Screenshot 2024-04-21 180419](https://github.com/safak/react-estate-ui/assets/1253732/e399a41b-6b74-4a76-9006-83776af59c21)

I need your help

**Comment by Qurbonov** [comment]
My mistake

**Comment by Qurbonov** [comment]
!

**Comment by ramakrishnan-21** [comment]
What you can do is add the following lines

```
const [open, setOpen] = useState(false);
    useEffect(() => {
        const handleResize = () => {
            if (window.innerWidth >= 768) { 
                setOpen(false);
            }
        };

        window.addEventListener('resize', handleResize);
        return () => window.removeEventListener('resize', handleResize);
    }, []);
    
```
    Basically on resize we have listener which will make setOpen as false and hence navbar will be hidden
